export const FILTER_PRODUCT = "FILTER_PRODUCT";
export const FILTER_CODE_PRODUCT = "FILTER_CODE_PRODUCT";
export const FILTER_TYPE = "FILTER_TYPE";
export const FILTER_PRODUCT_FOR = "FILTER_PRODUCT_FOR";
export const FILTER_ACCOUNT = "FILTER_ACCOUNT";
export const FILTER_USERNAME = "FILTER_USERNAME";
export const FILTER_PHONE = "FILTER_PHONE";