export const GET_USER = "GET_USER"
export const FILTER_USER = "FILTER_USER"
export const SUCCESS_USER = "SUCCESS_USER"
export const POST_USER = "POST_USER"
export const PUT_USER = "PUT_USER"
export const DELETE_USER = "DELETE_USER"