export const FILTER_PRODUCT = "FILTER_PRODUCT";
export const FILTER_CODE_PRODUCT = "FILTER_CODE_PRODUCT";
export const FILTER_TYPE = "FILTER_TYPE";
export const FILTER_PRODUCT_FOR = "FILTER_PRODUCT_FOR";

export const FILTER_ACCOUNT = "FILTER_ACCOUNT";
export const FILTER_USERNAME = "FILTER_USERNAME";
export const FILTER_PHONE = "FILTER_PHONE";

export const FILTER_ACCOUNT_ORDER = "FILTER_ACCOUNT_ORDER";
export const FILTER_NAME_ORDER = "FILTER_NAME_ORDER";
export const FILTER_PHONE_ORDER = "FILTER_PHONE_ORDER";
export const FILTER_ADDRESS_ORDER = "FILTER_ADDRESS_ORDER";