export const GET_TYPE = "GET_TYPE"
export const FILTER_TYPE = "FILTER_TYPE"
export const SUCCESS_TYPE = "SUCCESS_TYPE"
export const POST_TYPE = "POST_TYPE"
export const PUT_TYPE = "PUT_TYPE"
export const DELETE_TYPE = "DELETE_TYPE"